name: gespam_agua
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  http: ^0.12.0+2
  rflutter_alert: ^1.0.3
  progress_dialog: ^1.2.0
  json_serializable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/login.jpg
    - images/logo.png